# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Profile', verbose_name='A\u0432\u0442\u043e\u0440'),
        ),
    ]
