# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170522_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
