# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Answer', verbose_name='\u041e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
