# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170522_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='raiting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='raiting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
