# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20170523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
