# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_tag_num_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='raiting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='raiting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
